### ISSUE TITLE
Rework the water shader to look better

### ISSUE THREAD

**Issue by KikoMira** [KikoMira/Thrive-Planet-Generator-Example#3]

**Comment by DanyPapoudis** [comment]
https://github.com/KikoMira/Thrive-Planet-Generator-Example/pull/5

**Comment by DanyPapoudis** [comment]
This is my pull request

I think I solved your problem

https://github.com/KikoMira/Thrive-Planet-Generator-Example/pull/5

**Comment by KikoMira** [comment]
issue closed, thanks DanyPapoudis, this actually looks better than the one i had made
